version = 1

[install]

[vars]
ANDROID_API = "33"
ANDROID_EMULATOR_SERVICE = "android-emulator-max"

[hook]

[profile]

[services]

[include]
environments = [
    { dir = "./common" },
    { dir = "./min" },
    { dir = "./max" }
]

[build]

[options]
